spring:
  liquibase:
    change-log: classpath:liquibase/changelog.xml
    url: jdbc:h2:./aerospike-client;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    user: sa
    password: password

  datasource:
    url: jdbc:h2:./aerospike-client;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  resources:
    add-mappings: true