spring:
  liquibase:
    change-log: classpath:liquibase/changelog.xml
    url: jdbc:h2:./aerospike-client;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    user: sa
    password: password

  datasource:
    url: jdbc:h2:./aerospike-client;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  resources:
    add-mappings: true

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: ALWAYS

client:
  policy:
    read:
      socketTimeout: 3000
      totalTimeout: 5000
      sleepBetweenRetries: 100
      maxRetries: 3
    update:
      socketTimeout: 3000
      totalTimeout: 5000
      sleepBetweenRetries: 100
      maxRetries: 2
    create:
      socketTimeout: 3000
      totalTimeout: 5000
      sleepBetweenRetries: 100
      maxRetries: 2
    delete:
      socketTimeout: 3000
      totalTimeout: 5000
      sleepBetweenRetries: 100
      maxRetries: 2